### ISSUE TITLE
Shorten the titles of the webpages

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-docs#6]
Now they are too long and do not fit to the side menu easily.

**Comment by johpiip** [comment]
Ehdotuksia:

1. HSL:n liikenne-ennustejärjestelmän yleiskuvaus -> vasemmalla menussa "Etusivu" mutta itse sivun otsikko voi pysyä ennallaan "HSL:n liikenne-ennustejärjestelmän yleiskuvaus". Ainakin just-the-docsin livedemossa tällainen oli mahdollista.
2. Helmet 4.1 -liikenne-ennustejärjestelmän käyttöönotto -> Asennus
3. Sijoittelupankin perustaminen -> Sijoittelupankin perustaminen
4. Emme-verkon kuvaus -> Emme-verkon kuvaus
5. Mallijärjestelmän käyttöohje -> Mallijärjestelmän käyttö
6. Mallin lähtötietotiedostot ja niiden muokkaaminen -> Lähtötiedot
7. HSL:n ylläpitämät lähtötiedot -> Aineistojen ylläpito
8. Malliajon tulokset -> Tulokset
9. Ohje HSL:n mallitöiden tilaamiseen -> Mallitöiden tilausohje
10. HSL:n mallitöiden dokumentointiohje -> Mallitöiden dokumentointiohje
11. Esimerkkejä Helmet-mallilla tuotettavista tuloksista -> Esimerkkejä tuloksista

Miltä nämä kuulostaa esim. @eevavesaoja lle?
