### ISSUE TITLE
Put titles in order

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-docs#7]
The order should be the one that each file has in its `sort` keyword. This must work differently in this layout than in the previous.

Here is the `sort` keyword for "Emme-verkon kuvaus" page.
```
---
sort: 3
---

# Emme-verkon kuvaus

Tässä kerrotaan millä periaatteilla Emmen liikenneverkko ja joukkoliikennelinjasto on luotu.

[...]
```

Now, they are in alphabetical order:
![kuva](https://user-images.githubusercontent.com/20718745/236477302-3ad69edd-759c-48c8-989a-12d23fce30fc.png)

**Comment by hsl-petrhaj** [comment]
@johpiip Handled. 
nav_order parameter needed to be added to all the pages including the index page.
